server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      database: nosql
      uri: mongodb+srv://rTqLXnV4wIu1IH01:Maticheloeriruier71@cluster0.n6iau.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0