server:
  port: 8082

spring:
  r2dbc:
      url: r2dbc:postgresql://ep-little-violet-a5pwmroo-pooler.us-east-2.aws.neon.tech/sql?sslmode=require
      username: neondb_owner
      password: npg_8kV6FgLYaMWD
  sql:
    init:
      mode: always # Crea la tabla automáticamente al iniciar
      schema-locations: classpath:schema.sql # Archivo con la estructura de la tabla
      data-locations: classpath:data.sql # Archivo con datos iniciales (opcional)
  logging:
    level:
      org.springframework.r2dbc: DEBUG

